### PR TITLE
Use named enums and explicit std:: instead of "using namespace std"

### LINKED ISSUE #41: Calling RemoveHoles
This is for people who are having a bit of confusion about how to use the different triangulation methods on geometry with holes. (Maybe this could be included into the README for future users?)

Suppose you have a list of contours, some CCW and others CW (indicating holes). With the exception of `Triangulate_MONO`, you need to explicitly set CW contours to "holes" in the polygon.

Here is a little snippet to demonstrate this.
```
// convert contours to polygons using polypartition
for (auto contour : contours) {
    TPPLPoly poly;
    // set polygon points from contour. 
    // CCW for geometry and CW for holes

    // Need to manually call SetHole
    if (poly.GetOrientation() == TPPL_CW) {
        poly.SetHole(true);
    }
    polyList.push_back(poly);
}

TPPLPolyList tmpPolys;
// remove the holes
partition.RemoveHoles(&polyList, &tmpPolys);
// call triangulate function of your choice.
partition.Triangulate_EC(&tmpPolys, &outTriangles);
```

### PR DESCRIPTION
**Pull request by aaronfranke**
These changes increase the clarify of the API and make it harder to use it incorrectly (ex: you can't try to set an orientation of `2`).

I also updated the README with newlines and to mention that holes must be explicitly marked, which closes #41.

### CODE REVIEW

File: src/polypartition.cpp [hunk 1]
```diff
@@ -109,17 +97,17 @@ int TPPLPoly::GetOrientation() const {
...
-  return 0;
+  return TPPL_ORIENTATION_NONE;
 }
 
-void TPPLPoly::SetOrientation(int orientation) {
-  int polyorientation = GetOrientation();
-  if (polyorientation && (polyorientation != orientation)) {
+void TPPLPoly::SetOrientation(TPPLOrientation orientation) {
+  TPPLOrientation polyorientation = GetOrientation();
+  if (__glibc_likely(polyorientation != TPPL_ORIENTATION_NONE) && (polyorientation != orientation)) {
```
Comment (ivanfratric) [inline src/polypartition.cpp:110]: Will `__glibc_likely` work on all platforms though? I don't think it's part of the standard.

Comment (aaronfranke) [reply src/polypartition.cpp]: Good catch, it won't. I removed it. I'm surprised that the standard doesn't include anything like this.
